---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    - ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    - DOCKER_USR: "{{ lookup('env','DOCKER_USR') }}"
    - DOCKER_PWD: "{{ lookup('env','DOCKER_PWD') }}"

  pre_tasks:
    - name: "wait 60 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 60

    - name: "Install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    - configure-server
    

